# Sequel Pro dump
# Version 2492
# http://code.google.com/p/sequel-pro
#
# Host: localhost (MySQL 5.0.41)
# Database: locals_2010_analysis
# Generation Time: 2011-01-15 21:36:41 -0500
# ************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table original_posts
# ------------------------------------------------------------

DROP TABLE IF EXISTS `original_posts`;

CREATE TABLE `original_posts` (
  `id` int(11) NOT NULL auto_increment,
  `permalink` varchar(500) default NULL,
  `publication` varchar(20) default NULL,
  `title` varchar(500) default NULL,
  `pub_date` varchar(250) default NULL,
  `author` varchar(500) default NULL,
  `author_type` varchar(100) default NULL,
  `body_excerpt` text,
  `body_content_html` text,
  `post_category` varchar(100) default NULL,
  `post_tags` varchar(500) default NULL,
  `analysis_category` varchar(100) default NULL,
  `word_count` int(11) default NULL,
  `internal_links_count` int(11) default NULL,
  `external_links_count` int(11) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=100 DEFAULT CHARSET=latin1;

LOCK TABLES `original_posts` WRITE;
/*!40000 ALTER TABLE `original_posts` DISABLE KEYS */;
INSERT INTO `original_posts` (`id`,`permalink`,`publication`,`title`,`pub_date`,`author`,`author_type`,`body_excerpt`,`body_content_html`,`post_category`,`post_tags`,`analysis_category`,`word_count`,`internal_links_count`,`external_links_count`)
VALUES
	(1,'http://eastvillage.thelocal.nytimes.com/2010/11/30/amid-lost-eateries-savoring-vandaag/',NULL,NULL,NULL,NULL,NULL,'James Traub visits Vandaag on Second Avenue in the East Village, an eatery that describes itself as a ?bierrestaurantbakery.?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(2,'http://eastvillage.thelocal.nytimes.com/2010/11/30/in-cbgbs-basement-a-venue-rises/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits Extra Place, a venue located in the basement of the former C.B.G.B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(3,'http://eastvillage.thelocal.nytimes.com/2010/11/30/from-icon-to-unknown-and-loving-it/',NULL,NULL,NULL,NULL,NULL,'The Local East Village profiles Maria Popson, a former fashion model in Brazil who took a distinctive path to New York.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(4,'http://eastvillage.thelocal.nytimes.com/2010/11/30/the-day-the-east-village-nightscape/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including an item on how the proliferation of bars in the neighborhood as turned the community into a ?nightscape.?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(5,'http://eastvillage.thelocal.nytimes.com/2010/11/29/viewfinder-eastvillagedenizen/',NULL,NULL,NULL,NULL,NULL,'The photography of eastvillagedenizen, a community contributor to The Local East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(6,'http://eastvillage.thelocal.nytimes.com/2010/11/29/local-legends-peter-f-dailey/',NULL,NULL,NULL,NULL,NULL,'Historian Tim Milk recounts the life of Peter F. Dailey, a 19th century pioneer of improvisational comedy who grew up in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(7,'http://eastvillage.thelocal.nytimes.com/2010/11/29/extension-cord-cited-in-fire/',NULL,NULL,NULL,NULL,NULL,'A small fire on East 10th Street this morning was sparked by an extension cord that melted after being wrapped around a radiator in a fifth floor apartment, the authorities said. ?Luckily, the tenant was home,? said John Bley, the chief of Division 1, adding that the fire could have been much worse had the [...]',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(8,'http://eastvillage.thelocal.nytimes.com/2010/11/29/the-day-nostalgia-takes-a-bow/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including a series of nostalgic looks at neighborhood history and an interview with the new owner of the Polonia Restaurant.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(9,'http://eastvillage.thelocal.nytimes.com/2010/11/26/viewfinder-autumn-gardens/',NULL,NULL,NULL,NULL,NULL,'Photographer Gloria Chung visits gardens in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(10,'http://eastvillage.thelocal.nytimes.com/2010/11/26/on-7th-st-a-martial-art-and-more/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits the Nisei Goju International Headquarters where students learn a martial art that borrows from karate and jiujitsu.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(11,'http://eastvillage.thelocal.nytimes.com/2010/11/26/in-the-park-still-searching-for-sammy/',NULL,NULL,NULL,NULL,NULL,'The Local reports on the latest developments in the search for Sammy, a shaved Pomeranian that has been missing since June and was last seen in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(12,'http://eastvillage.thelocal.nytimes.com/2010/11/26/the-day-on-tweets-and-firehouses/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including items about a neighborhood firehouse?s Twitter account and The Local?s search for its next community editor.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(13,'http://eastvillage.thelocal.nytimes.com/2010/11/25/the-day-with-our-thanks/',NULL,NULL,NULL,NULL,NULL,'The Local expresses its gratitude to the students, photographers and East Village residents who have shared their talents with the site.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(14,'http://eastvillage.thelocal.nytimes.com/2010/11/24/by-the-numbers-a-meal-for-5000/',NULL,NULL,NULL,NULL,NULL,'The Local visits the Bowery Mission where volunteers have been hard at work preparing a meal for 5,000 people.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(15,'http://eastvillage.thelocal.nytimes.com/2010/11/24/or-making-dinner-for-just-a-few/',NULL,NULL,NULL,NULL,NULL,'The Local goes shopping for Thanksgiving dinner with several East Village residents and compares shopping lists ? and prices.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(16,'http://eastvillage.thelocal.nytimes.com/2010/11/24/a-look-at-some-multinational-feasts/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits neighborhood restaurant that celebrate post-Pilgrim immigrant cuisine.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(17,'http://eastvillage.thelocal.nytimes.com/2010/11/24/the-day-on-murals-and-mr-west/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including items about a not-so-surprise concert by Kanye West and the newest mural at Bowery and Houston.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(18,'http://eastvillage.thelocal.nytimes.com/2010/11/23/finding-the-best-vintage-clothing-buys/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits neighborhood vintage and consignment stores.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(19,'http://eastvillage.thelocal.nytimes.com/2010/11/23/on-12th-st-learning-to-keep-it-real/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits the Reality TV School of New York where students to learn how to be themselves ? only better.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(20,'http://eastvillage.thelocal.nytimes.com/2010/11/23/local-legends-the-monkey-thief/',NULL,NULL,NULL,NULL,NULL,'East Village historian Tim Milk takes a look at a neighborhood legend about a particularly nimble burglar.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(21,'http://eastvillage.thelocal.nytimes.com/2010/11/23/the-day-bus-lanes-and-bike-lanes/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including posts about new surveillance cameras along the M15 bus route and the continuing debate over bike lanes.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(22,'http://eastvillage.thelocal.nytimes.com/2010/11/22/viewfinder-crusty-punks/',NULL,NULL,NULL,NULL,NULL,'Photographer Steven Hirsch documents the tribe of tattooed denizens who hang out on Crusty Row in Tompkins Square Park in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(23,'http://eastvillage.thelocal.nytimes.com/2010/11/22/getting-an-earful-of-zombie-jazz/',NULL,NULL,NULL,NULL,NULL,'The Local East Village profiles Father Figures, a group composed of five friends who describe their music as ?zombie jazz,? ? an effort to resurrect a dying breed of jazz musicians with its strong improvisational sounds, eclectic inspirations, and a distinct blend of fun.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(24,'http://eastvillage.thelocal.nytimes.com/2010/11/22/east-village-with-all-the-trimmings/',NULL,NULL,NULL,NULL,NULL,'The Local examines a range of alternative dining options at East Village restaurants for those spending Turkey Day away from home.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(25,'http://eastvillage.thelocal.nytimes.com/2010/11/22/on-broadway-a-geeked-out-storefront/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits the new Wired store at Broadway and East Fourth Street, which offers a range of holiday gifts for the geek in your life.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(26,'http://eastvillage.thelocal.nytimes.com/2010/11/22/the-day-4th-st-development-details/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including what?s in store for two properties that preservationists unsuccessfully sought to keep from being re-developed and kudos to a neighborhood finalist on ?The Next Iron Chef.?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(27,'http://eastvillage.thelocal.nytimes.com/2010/11/19/viewfinder-vivienne-gucwa/',NULL,NULL,NULL,NULL,NULL,'The photography of Vivienne Gucwa, a community contributor to The Local East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(28,'http://eastvillage.thelocal.nytimes.com/2010/11/19/for-wine-lovers-an-anticipated-debut/',NULL,NULL,NULL,NULL,NULL,'Wine lovers in the East Village joined connoisseurs around the world in welcoming Beaujolais Nouveau, the young, fruity, barely fermented (and to some, barely drinkable) wine that hit the shelves and bars Thursday night.\n',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(29,'http://eastvillage.thelocal.nytimes.com/2010/11/19/the-many-flavors-of-pumpkins/',NULL,NULL,NULL,NULL,NULL,'The Local visits East Village restaurants that specialize in making dishes out of pumpkins.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(30,'http://eastvillage.thelocal.nytimes.com/2010/11/19/portraits-john-derobertis/',NULL,NULL,NULL,NULL,NULL,'Photographer John Galayda visits the DeRobertis Caffee in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(31,'http://eastvillage.thelocal.nytimes.com/2010/11/19/permits-issued-to-developer/',NULL,NULL,NULL,NULL,NULL,'On the same day that a preservation group held a news conference urging the Landmarks Preservation Commission to reconsider designating a pair of 170-year old buildings at 326 and 328 East Fourth Street as historic landmarks, the Department of Buildings awarded permits for both buildings to developer Terrence Lowenberg.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(32,'http://eastvillage.thelocal.nytimes.com/2010/11/19/n-y-u-expansion-plan-changes-course/',NULL,NULL,NULL,NULL,NULL,'When New York University announced that it was abandoning a proposal to build a fourth structure on the Silver Towers site, it changed the direction of its expansion plan.\nActivists opposing New York University?s ?2031 Plan? for expansion won?t have the ?Silver Sliver? to kick around anymore.\nThat was the news yesterday afternoon as the university announced [...]',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(33,'http://eastvillage.thelocal.nytimes.com/2010/11/19/the-day-restoring-st-brigids/',NULL,NULL,NULL,NULL,NULL,'A roundup on blogposts related to the East Village, including items about the cost of restoring St. Brigid?s Church and the lingering resonance of Bowery-inspired slang.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(34,'http://eastvillage.thelocal.nytimes.com/2010/11/18/street-style-a-look-at-fall-boots/',NULL,NULL,NULL,NULL,NULL,'The Local East Village examines the latest styles for fall boots.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(35,'http://eastvillage.thelocal.nytimes.com/2010/11/18/n-y-u-abandons-tower-plan/',NULL,NULL,NULL,NULL,NULL,'New York University announced today that it would not be pursuing plans to build a 400-foot residential tower and hotel on Bleecker Street.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(36,'http://eastvillage.thelocal.nytimes.com/2010/11/18/the-secret-bars-of-the-east-village/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits some of the neighborhood?s secret ? and not-so-secret ? bars.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(37,'http://eastvillage.thelocal.nytimes.com/2010/11/18/the-scaffolding-workout/',NULL,NULL,NULL,NULL,NULL,'The Local East Village explores improvised personal fitness work outs on scaffolding.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(38,'http://eastvillage.thelocal.nytimes.com/2010/11/18/the-day-more-on-the-missing-mural/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including items about the mural of President Obama on Sixth and C and a look at an epic fire in the 1950s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(39,'http://eastvillage.thelocal.nytimes.com/2010/11/17/the-most-child-friendly-restaurants/',NULL,NULL,NULL,NULL,NULL,'The Local East Village takes a look at some neighborhood restaurants that make dining out with children a breeze.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(40,'http://eastvillage.thelocal.nytimes.com/2010/11/17/learning-to-make-the-perfect-cupcake/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits Butter Lane, a small boutique bake shop on Seventh Street that offers classes in cupcake making.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(41,'http://eastvillage.thelocal.nytimes.com/2010/11/17/on-14th-st-a-hoarders-paradise/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits Russian Souvenirs, a small consignment store on 14th Street near Third Avenue that has some of the most unusual finds in the neighborhood.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(42,'http://eastvillage.thelocal.nytimes.com/2010/11/17/the-day-more-preservation-blues/',NULL,NULL,NULL,NULL,NULL,'A roundup of blog posts related to the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(43,'http://eastvillage.thelocal.nytimes.com/2010/11/16/a-soiree-with-the-arts-in-mind/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits the Quarterly Arts Soiree at Webster Hall.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(44,'http://eastvillage.thelocal.nytimes.com/2010/11/16/grading-the-cleanliness-of-pizzerias/',NULL,NULL,NULL,NULL,NULL,'The Local East Village looks at the results of health inspections at neighborhood pizzerias.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(45,'http://eastvillage.thelocal.nytimes.com/2010/11/16/two-refused-by-liquor-license-panel/',NULL,NULL,NULL,NULL,NULL,'A Community Board panel Monday night voted against plans to reopen two bars on Avenue A, despite pre-emptive efforts by business owners to smooth things over with East Village residents fed up with noisy nightlife in their neighborhood.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(46,'http://eastvillage.thelocal.nytimes.com/2010/11/15/on-first-ave-a-graffiti-artists-return/',NULL,NULL,NULL,NULL,NULL,'A newspaper distribution box in the East Village now showcases the first major public work of art in more than a decade for one of New York City?s most infamous graffiti artists, Adam Cole, a.k.a. Cost.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(47,'http://eastvillage.thelocal.nytimes.com/2010/11/15/on-st-marks-the-joys-of-dumplings/',NULL,NULL,NULL,NULL,NULL,'James Traub visits The Dumpling Man on St. Marks Place.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(48,'http://eastvillage.thelocal.nytimes.com/2010/11/15/a-fusion-of-buddhism-and-punk-rock/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits Dharma Punx, a free, walk-in meditation class that fuses the tenets of Buddhism and punk rock.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(49,'http://eastvillage.thelocal.nytimes.com/2010/11/15/preserving-history-on-the-bowery/',NULL,NULL,NULL,NULL,NULL,'The Local East Village interviews David Mulkins, chair of the Bowery Alliance of Neighbors.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(50,'http://eastvillage.thelocal.nytimes.com/2010/11/15/in-tompkins-square-jazz-for-all/',NULL,NULL,NULL,NULL,NULL,'The Local East Village visits with Giuseppi Logan who continues to play his saxophone well into the fall season at Tompkins Square Park.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(51,'http://eastvillage.thelocal.nytimes.com/2010/11/15/the-day-a-scare-at-an-iconic-address/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including a fire scare at an apartment building on St. Marks Place that was featured on the cover of Led Zeppelin?s 1975 album ?Physical Graffiti.?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(52,'http://eastvillage.thelocal.nytimes.com/2010/11/12/viewfinder-sarah-tung/',NULL,NULL,NULL,NULL,NULL,'The photography of NYU Journalism?s Sarah Tung.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(53,'http://eastvillage.thelocal.nytimes.com/2010/11/12/singer-explores-pain-of-mental-illness/',NULL,NULL,NULL,NULL,NULL,'Susan McKeown, the Grammy Award-winning songwriter who has lived in the East Village for 20 years, has released a new album, ?Singing in the Dark,? which explores her family?s history of mental illness.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(54,'http://eastvillage.thelocal.nytimes.com/2010/11/12/in-the-east-village-a-craft-beer-hub/',NULL,NULL,NULL,NULL,NULL,'Once a niche drink, craft beers are tapping new devoted drinkers, especially in the East Village. Good Beer on East Ninth Street became the latest craft beer purveyor when it opened its doors on Tuesday.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(55,'http://eastvillage.thelocal.nytimes.com/2010/11/12/the-best-places-to-find-a-date/',NULL,NULL,NULL,NULL,NULL,'The Local takes to the streets to ask: ?Where?s the best place to meet a potential date in the East Village??',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(56,'http://eastvillage.thelocal.nytimes.com/2010/11/12/locals-jack-germain/',NULL,NULL,NULL,NULL,NULL,'Maya Millett Handbag designer Jack Germain, who resides in Alphabet City, shows off her upcoming spring collection.\nWhen The Local first encountered handbag designer and fashion blogger Jack Germain, she was rushing to get a manicure in preparation for her 25th birthday party. It was one of the season?s first truly autumn days, and Ms. Germain, [...]',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(57,'http://eastvillage.thelocal.nytimes.com/2010/11/12/on-2nd-ave-a-haven-for-libertarians/',NULL,NULL,NULL,NULL,NULL,'The Local East Village attends a neighborhood meeting of the Libertarian Party, where members gather to share their fiscally conservative, socially liberal ideology and some spinach pierogis.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(58,'http://eastvillage.thelocal.nytimes.com/2010/11/12/angry-tenants-take-landlord-to-court/',NULL,NULL,NULL,NULL,NULL,'The residents of 114 East First Street ? where a third of the building?s apartments were recently without cooking gas for 138 days and where vermin have colonized the garbage area ? take their landlord to court today.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(59,'http://eastvillage.thelocal.nytimes.com/2010/11/12/the-day-fight-against-bar-continues/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including news about the Sin Sin Lounge and a recent Lady Gaga sighting at a Lower East Side yoga studio.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(60,'http://eastvillage.thelocal.nytimes.com/2010/11/11/stabbing-victims-sister-mourns-loss/',NULL,NULL,NULL,NULL,NULL,'After a judge deems Jairo Pastoressa ?mentally unfit? to stand trial in the fatal stabbing of Christopher Jusko in the East Village last month, the sister of the victim and others reflect.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(61,'http://eastvillage.thelocal.nytimes.com/2010/11/11/seven-hospitalized-after-high-rise-fire/',NULL,NULL,NULL,NULL,NULL,'Seven people were hospitalized with minor injuries this morning after a blaze ripped through a sixth-floor apartment of the Ageloff Towers on Fourth Street in the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(62,'http://eastvillage.thelocal.nytimes.com/2010/11/10/from-students-green-energy-lessons/',NULL,NULL,NULL,NULL,NULL,'A non-profit group specializing in sustainability has appointed a half-dozen high school students to act as green energy consultants to small businesses here in the East Village. The Local follows a group of students as they canvass the neighborhood.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(63,'http://eastvillage.thelocal.nytimes.com/2010/11/10/examining-m15-bus-line-changes/',NULL,NULL,NULL,NULL,NULL,'Amid news that the MTA is working to improve efficiency on the M15 bus line, The Local East Village offers a special report on recent changes to the route. In a pair of posts, reporters for The Local speak with riders on the route and offer an analysis of whether the new system is achieving its goals.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(64,'http://eastvillage.thelocal.nytimes.com/2010/11/10/the-day-from-disco-to-momofuku/',NULL,NULL,NULL,NULL,NULL,'Vivienne Gucwa\nGood morning, East Village.\nEnjoy an old school start to your day by following Sheryl Lee Ralph?s lead as she grooves through an almost unrecognizable East Village in her 1984 video for ?In the Evening,? resurrected by Jeremiah?s Vanishing New York.\nOn a less upbeat note, EV Grieve has photographs of the makeshift ?for rent? signs [...]',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(65,'http://eastvillage.thelocal.nytimes.com/2010/11/09/one-more-chance-to-hear-annie/',NULL,NULL,NULL,NULL,NULL,'An audio recording made by an East Village resident in July offers listeners another chance to hear the voice of the beloved neighborhood fixture Gloria Wasserman, who known as Annie.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(66,'http://eastvillage.thelocal.nytimes.com/2010/11/09/in-the-east-village-its-a-chefs-life/',NULL,NULL,NULL,NULL,NULL,'Over the last few years, the East Village has become one of the city?s premier dining neighborhoods. Alongside the inexpensive pizzerias, the discount sushi, and the tandoori restaurants of East Sixth, serious restaurants have established themselves. The Local spends a day with Matt Hamilton, chef and partner in the Second Avenue restaurant Belcourt, to answer a simple question: What makes these places run?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(67,'http://eastvillage.thelocal.nytimes.com/2010/11/09/an-officers-tales-of-life-on-ave-d/',NULL,NULL,NULL,NULL,NULL,'Michael Codella, a former police detective, is the author of ?Alphaville,? a new book that describes his years working the streets of the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(68,'http://eastvillage.thelocal.nytimes.com/2010/11/09/plan-aims-to-improve-m15-bus-service/',NULL,NULL,NULL,NULL,NULL,'After major changes last month along the M15 bus route in the East Village, MTA officials are putting new measures in place this week to improve efficiency along the line.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(69,'http://eastvillage.thelocal.nytimes.com/2010/11/09/the-day-welcoming-a-new-blog/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including a new local blog, EV Transitions, and The Local?s search for our next community editor.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(70,'http://eastvillage.thelocal.nytimes.com/2010/11/08/at-la-palapa-a-mix-of-mexican-foods/',NULL,NULL,NULL,NULL,NULL,'James Traub samples the ?house-made? Mexican cuisine at La Palapa.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(71,'http://eastvillage.thelocal.nytimes.com/2010/11/08/seeking-the-next-community-editor/',NULL,NULL,NULL,NULL,NULL,'As the tenure of Kim Davis as community editor of The Local East Village draws to a close, the blog announces that it is accepting applications for the position until Dec. 3.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(72,'http://eastvillage.thelocal.nytimes.com/2010/11/08/on-4th-st-an-iconic-sandal-maker/',NULL,NULL,NULL,NULL,NULL,'An interview with Barbara Shaum, who has been fashioning sandals at her store on East Fourth Street for more than 50 years.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(73,'http://eastvillage.thelocal.nytimes.com/2010/11/08/in-the-east-village-kicking-the-habit/',NULL,NULL,NULL,NULL,NULL,'The Local East Village reports on one woman?s battle to beat her addiction to heroin.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(74,'http://eastvillage.thelocal.nytimes.com/2010/11/08/the-day-quiet-streets-vintage-photos/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including archival photos from the New York Public Library, a tribute to a beloved local bartender and the filming of a new Chris Rock movie, 2 Days in New York.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(75,'http://eastvillage.thelocal.nytimes.com/2010/11/05/street-style-whats-your-fall-look/',NULL,NULL,NULL,NULL,NULL,'The Local East Village takes a look at some of the most distinctive styles in the neighborhood.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(76,'http://eastvillage.thelocal.nytimes.com/2010/11/05/an-east-village-jazz-gem-at-rue-b/',NULL,NULL,NULL,NULL,NULL,'A review of Rue B., an East Village jazz club on Avenue B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(77,'http://eastvillage.thelocal.nytimes.com/2010/11/05/introducing-our-social-media-team/',NULL,NULL,NULL,NULL,NULL,'Introducing the students of NYU Journalism who are directing The Local?s social media effort.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(78,'http://eastvillage.thelocal.nytimes.com/2010/11/05/rights-protest-becomes-hunger-strike/',NULL,NULL,NULL,NULL,NULL,'Earlier this week, a gay rights activist who has maintained a monthlong sidewalk protest outside the local office of Senator Kristen Gillibrand began a hunger strike to draw attention to the American Equality Bill.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(79,'http://eastvillage.thelocal.nytimes.com/2010/11/05/the-day-haunted-houses-trick-shots/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village, including items about a possible haunted house on East 13th Street and a video of trick basketball shots filmed on local courts.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(80,'http://eastvillage.thelocal.nytimes.com/2010/11/04/in-the-east-village-a-cownapping/',NULL,NULL,NULL,NULL,NULL,'The owners of The Sunburnt Cow, an East Village bar, are offering a $500 reward for the return of the tavern?s sign which depicts a miniature cow.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(81,'http://eastvillage.thelocal.nytimes.com/2010/11/04/on-ave-c-cutting-hair-hanging-out/',NULL,NULL,NULL,NULL,NULL,'A visit to the Perfection Barber Shop on Avenue C, which has quickly become a neighborhood gathering place.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(82,'http://eastvillage.thelocal.nytimes.com/2010/11/04/on-the-east-river-building-a-bulwark/',NULL,NULL,NULL,NULL,NULL,'The Local East Village profiles Jim Scileppi, who has operated cranes on barges for two decades.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(83,'http://eastvillage.thelocal.nytimes.com/2010/11/04/interview-daniel-l-squadron/',NULL,NULL,NULL,NULL,NULL,'The Local East Village interviews State Senator Daniel L. Squadron, who outlines the legislative agenda for his next term, including new laws to combat noise and increase pedestrian safety.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(84,'http://eastvillage.thelocal.nytimes.com/2010/11/04/the-day-the-protest-that-wasnt/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(85,'http://eastvillage.thelocal.nytimes.com/2010/11/03/viewfinder-rachel-wise/',NULL,NULL,NULL,NULL,NULL,'The photography of NYU Journalism?s Rachel Wise.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(86,'http://eastvillage.thelocal.nytimes.com/2010/11/03/is-the-recession-over/',NULL,NULL,NULL,NULL,NULL,'The students of NYU Journalism?s Reporting New York and Reporting the Nation concentration took the streets of the East Village to ask a simple question: Do think the recession is over?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(87,'http://eastvillage.thelocal.nytimes.com/2010/11/03/the-day-on-poets-and-artists/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(88,'http://eastvillage.thelocal.nytimes.com/2010/11/03/east-village-election-issues/',NULL,NULL,NULL,NULL,NULL,'A look at the results of local races and a discussion of how East Village issues such as noise complaints played a role in Tuesday?s balloting.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(89,'http://eastvillage.thelocal.nytimes.com/2010/11/02/an-analysis-of-east-village-elections/',NULL,NULL,NULL,NULL,NULL,'An analysis of the likely winners and losers in today?s election.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(90,'http://eastvillage.thelocal.nytimes.com/2010/11/02/taking-the-pulse-of-east-village-poetry/',NULL,NULL,NULL,NULL,NULL,'An examination of the East Village?s poetry scene, including visits to the Nuyorican Poets Cafe, the Bowery Poetry Club and the Poetry Project at St. Mark?s.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(91,'http://eastvillage.thelocal.nytimes.com/2010/11/02/portraits-dia-de-los-muertos/',NULL,NULL,NULL,NULL,NULL,'The Local East Village looks at celebrations of Dia De Los Muertos, the Day of the Dead.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(92,'http://eastvillage.thelocal.nytimes.com/2010/11/02/locals-john-penley/',NULL,NULL,NULL,NULL,NULL,'An interview with East Village community activist John Penley.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(93,'http://eastvillage.thelocal.nytimes.com/2010/11/02/the-day-getting-licensed-and-getting-around/',NULL,NULL,NULL,NULL,NULL,'A roundup of blogposts related to the East Village.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(94,'http://eastvillage.thelocal.nytimes.com/2010/11/01/at-graffiti-an-eclectic-blend-of-styles/',NULL,NULL,NULL,NULL,NULL,'James Traub samples the eclectic flavors of Graffiti, an East Village restaurant where the cuisine is described as ?Persian and Indian spices with French and American technique.?',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(95,'http://eastvillage.thelocal.nytimes.com/2010/11/01/all-quiet-in-tompkins-square-park/',NULL,NULL,NULL,NULL,NULL,'The East Village community failed to turn out on the night of Halloween in support of a protest against Community Board 3?s proposed volume restrictions on concerts in Tompkins Square Park.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(96,'http://eastvillage.thelocal.nytimes.com/2010/11/01/celebrating-the-day-of-the-dead/',NULL,NULL,NULL,NULL,NULL,'A weekend festival at an East Village church marked the annual celebration of Dia de los Muertos, or Day of the Dead.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(97,'http://eastvillage.thelocal.nytimes.com/2010/11/01/a-new-home-for-the-girls-club/',NULL,NULL,NULL,NULL,NULL,'The actress Rosario Dawson attended a ground-breaking ceremony in the East Village Friday for the new home of the Lower Eastside Girls Club.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(98,'http://eastvillage.thelocal.nytimes.com/2010/11/01/east-village-halloween-scenes/',NULL,NULL,NULL,NULL,NULL,'Scenes and snapshots taken from around the East Village on Halloween.',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(99,'http://eastvillage.thelocal.nytimes.com/2010/11/01/interview-kristin-m-davis/',NULL,NULL,NULL,NULL,NULL,'The Local East Village interviews Kristin M. Davis, the Anti-Prohibition Party candidate for governor of New York.',NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40000 ALTER TABLE `original_posts` ENABLE KEYS */;
UNLOCK TABLES;





/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
